
#import "../utils.typ" : *
#import "@preview/curryst:0.6.0": rule, prooftree
#import "@preview/subpar:0.2.2" as subpar: grid as spg
#import "@preview/fletcher:0.5.8" as fletcher: diagram, node, edge
#import "@preview/diagraph:0.3.6": raw-render as grender

== Inductive predicate

#let code-math(code, mmath, c, ccode : [Inductive Notation], cmath : [Polynomial], lab : none) = [
  #set math.equation(numbering: none)
  #spg(
  figure(code, caption: ccode),
  figure(mmath, caption: cmath),
  columns: (1fr, 1fr),
  caption: c,
  label: lab
) ]

An inductive predicate is a least fixed point;
a universal quantification over all relations of a given shape.
An example of an inductive predicate is evenness.
This is defined as a higher-order predicate called the `Shape` in this case,
we use this to restrict the relations we are talking about.
Then we take the universal over this shape and we get what is shown in @ipred:fg:iseven.
It can be shown that this definition is equal to the one generated by the expected Lean code.

#code-math(raw(read("./IsEven.lean"), lang: "lean", block: true),
  ccode: [],
  $
  "shape"_P  &eq.delta P 0 and forall n, P n -> P (n + 2) \
  "Even" (n) &eq.delta forall P, "shape"_P -> P n \
  e_0 : "Even" 0 &eq.delta lambda P "hP". pi_1 ("hP")
  $,
  cmath: [],
  [Evenness inductive predicate, from first principles],
  lab: <ipred:fg:iseven>
)

== Coinductive predicate <sec:coindp>

// TODO: remove this section 

Given what we saw in the last section and how we have seen the duality for coinductive and inductive data;
all we must do is dualize this construction.
So we change the universal to an existential, disjuncts to conjuncts,
and flip the arrows (each of these swap left and right adjoints).
This gives us a proof principal with three components.
We now need to define an invariant,
we need to prove the invariant satisfies the restriction,
and that our value is contained in the invariant.

Proving coinductive predicates is challenging as it requires coming up with the invariant.
This is a kind of proof I had no experience in,
and it took a while to pick up.
An additional difficulty is,
if you get the invariant wrong,
you have to start completely again and try to come up with something better.
This means that for some of my proofs I wrote hundreds of lines of code that have not made it into the dissertation.

Some languages have facilities to make this better,
these are collectively known as coinduction-up-to.
These are techniques where you can reuse earlier proofs and automatically expand the invariant.
For Rocq a popular library for this is Paco#footnote[TODO CITE],
a lot of harder coinduction proofs use this technique.
Lean does not have this feature,
and it is out of scope for the dissertation.
In its place I spend a lot of time picking the shape of the Invariant I need.

